# Generated by Django 2.1.2 on 2018-11-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0003_auto_20181111_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='boarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_boarding', models.DateTimeField(auto_now_add=True)),
                ('days_of_stay', models.IntegerField(default=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyPaws.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HappyPaws.owner')),
            ],
        ),
    ]
