# Generated by Django 2.1.2 on 2018-11-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0007_dog_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='test', max_length=128, unique='True'),
            preserve_default=False,
        ),
    ]
