# Generated by Django 2.1.2 on 2018-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0008_owner_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=128, primary_key=True, serialize=True),
        ),
    ]
