# Generated by Django 2.1.2 on 2018-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0009_auto_20181118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
