# Generated by Django 2.1.2 on 2018-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0010_auto_20181119_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='size',
            field=models.CharField(default='small', max_length=32),
            preserve_default=False,
        ),
    ]
