# Generated by Django 2.1.2 on 2018-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0012_auto_20181130_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='grooming',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HappyPaws.pricing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
