# Generated by Django 2.1.2 on 2018-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyPaws', '0013_auto_20181202_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grooming',
            name='price',
            field=models.IntegerField(),
        ),
    ]
